# Generated by Django 5.2.8 on 2026-01-09 19:08

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=diary.models.current_month),
        ),
        migrations.AddField(
            model_name='diary',
            name='year',
            field=models.PositiveSmallIntegerField(default=diary.models.current_year),
        ),
    ]
