# Generated by Django 5.2.8 on 2026-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_question_options_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
